-- User-Defined Database Schemas
-- Generated by ProjexLight CLI Export System
-- Database: postgresql
-- Total Schemas: 1

-- ========================================
-- Schema: Rider App Schema
-- Description: Auto-generated database schema for Rider App. Generated from project description...
-- Version: 1
-- ========================================

CREATE TABLE IF NOT EXISTS ride_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID,
  start_location VARCHAR(255),
  end_location VARCHAR(255),
  timestamp TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ride_requests IS 'Schema: Rider App Schema - Entity: Ride_requests';

CREATE TABLE IF NOT EXISTS ride_matches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  request_id UUID,
  driver_id UUID,
  matched_time VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ride_matches IS 'Schema: Rider App Schema - Entity: Ride_matches';

CREATE TABLE IF NOT EXISTS ride_costs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ride_id UUID,
  total_cost DECIMAL(10,2),
  split_cost DECIMAL(10,2),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ride_costs IS 'Schema: Rider App Schema - Entity: Ride_costs';

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255),
  email VARCHAR(255),
  password_hash VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE users IS 'Schema: Rider App Schema - Entity: Users';

CREATE TABLE IF NOT EXISTS drivers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID,
  vehicle_id UUID,
  verification_status VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE drivers IS 'Schema: Rider App Schema - Entity: Drivers';

CREATE TABLE IF NOT EXISTS ride_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID,
  ride_id UUID,
  timestamp TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ride_history IS 'Schema: Rider App Schema - Entity: Ride_history';

CREATE TABLE IF NOT EXISTS ride_tracking (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ride_id UUID,
  location_data VARCHAR(255),
  timestamp TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ride_tracking IS 'Schema: Rider App Schema - Entity: Ride_tracking';

CREATE TABLE IF NOT EXISTS ride_feedback (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ride_id UUID,
  user_id UUID,
  rating VARCHAR(255),
  comments VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ride_feedback IS 'Schema: Rider App Schema - Entity: Ride_feedback';

CREATE TABLE IF NOT EXISTS messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sender_id UUID,
  receiver_id UUID,
  content TEXT,
  timestamp TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE messages IS 'Schema: Rider App Schema - Entity: Messages';

